# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDisplay.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SV_mainDisplay(object):
    def setupUi(self, SV_mainDisplay):
        SV_mainDisplay.setObjectName("SV_mainDisplay")
        SV_mainDisplay.resize(1280, 800)
        SV_mainDisplay.setStyleSheet(".QFrame{background-image: url(:/images/darkbg.jpg);}")
        self.centralwidget = QtWidgets.QWidget(SV_mainDisplay)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.frame.setStyleSheet("#grTopMain{background-color: rgb(0, 0, 0);color: rgb(255, 255, 255);}QGroupBox {border: 2px solid #FFAB91;border-radius: 10px;}QPushButton:pressed { background-color: #FF6E40}.QPushButton{border-radius: 20px;background-color: #FFC107;font: 75 20pt bold \"Ubuntu\";}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.grTopMain = QtWidgets.QGroupBox(self.frame)
        self.grTopMain.setGeometry(QtCore.QRect(0, 729, 1281, 71))
        self.grTopMain.setStyleSheet("#grTopMain{ border: 0px solid gray; border-radius: 0px; }.QLabel {font: 57 bold 22pt \"Ubuntu\";color: rgb(255, 255, 255);}")
        self.grTopMain.setTitle("")
        self.grTopMain.setObjectName("grTopMain")
        self.label = QtWidgets.QLabel(self.grTopMain)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 60))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.grTopMain)
        self.label_2.setGeometry(QtCore.QRect(530, -1, 741, 61))
        
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.grTempOut = QtWidgets.QGroupBox(self.frame)
        self.grTempOut.setGeometry(QtCore.QRect(690, 120, 581, 171))
        self.grTempOut.setStyleSheet(".QLabel{color: rgb(255, 255, 255);font: 75 20pt \"Ubuntu\";}#lbTempOutValue{color: rgb(255, 0,0);font: 75 Bold 22pt \"Ubuntu\";}#lbHumiOutValue{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}#lbTempInValue{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}#lbHumiInValue{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}")
        self.grTempOut.setTitle("")
        self.grTempOut.setObjectName("grTempOut")
        self.lbTempIn_2 = QtWidgets.QLabel(self.grTempOut)
        self.lbTempIn_2.setGeometry(QtCore.QRect(10, 60, 201, 45))
        self.lbTempIn_2.setObjectName("lbTempIn_2")
        self.lbHumiIn_2 = QtWidgets.QLabel(self.grTempOut)
        self.lbHumiIn_2.setGeometry(QtCore.QRect(300, 60, 191, 45))
        self.lbHumiIn_2.setObjectName("lbHumiIn_2")
        self.lbTempOutValue = QtWidgets.QLabel(self.grTempOut)
        self.lbTempOutValue.setGeometry(QtCore.QRect(210, 60, 81, 45))
        self.lbTempOutValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTempOutValue.setObjectName("lbTempOutValue")
        self.lbHumiOutValue = QtWidgets.QLabel(self.grTempOut)
        self.lbHumiOutValue.setGeometry(QtCore.QRect(500, 60, 81, 45))
        self.lbHumiOutValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lbHumiOutValue.setObjectName("lbHumiOutValue")
        self.lbTempInValue = QtWidgets.QLabel(self.grTempOut)
        self.lbTempInValue.setGeometry(QtCore.QRect(210, 20, 81, 45))
        self.lbTempInValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTempInValue.setObjectName("lbTempInValue")
        self.lbTempIn = QtWidgets.QLabel(self.grTempOut)
        self.lbTempIn.setGeometry(QtCore.QRect(10, 20, 201, 45))
        self.lbTempIn.setObjectName("lbTempIn")
        self.lbHumiInValue = QtWidgets.QLabel(self.grTempOut)
        self.lbHumiInValue.setGeometry(QtCore.QRect(500, 20, 81, 45))
        self.lbHumiInValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lbHumiInValue.setObjectName("lbHumiInValue")
        self.lbHumiIn = QtWidgets.QLabel(self.grTempOut)
        self.lbHumiIn.setGeometry(QtCore.QRect(300, 20, 191, 41))
        self.lbHumiIn.setObjectName("lbHumiIn")
        self.grStatusMotor = QtWidgets.QGroupBox(self.frame)
        self.grStatusMotor.setGeometry(QtCore.QRect(10, 120, 481, 171))
        self.grStatusMotor.setStyleSheet(".QLabel{color: rgb(255, 255, 255);font: 75  20pt \"Ubuntu\";}\n"
                "#lbTrangThaiLuuTru{color:#FFFF00 ;font: 75  22pt \"Ubuntu\";}\n"
                "#lbChoMuon{color :#D500F9;font:75 bold 22pt \"Ubuntu\";}\n"
                "#lbTrongKho{color :#D500F9;font:75  bold 22pt \"Ubuntu\";}\n"
                "")
        self.grStatusMotor.setTitle("")
        self.grStatusMotor.setObjectName("grStatusMotor")
        self.lbTrangThaiLuuTru = QtWidgets.QLabel(self.grStatusMotor)
        self.lbTrangThaiLuuTru.setGeometry(QtCore.QRect(110, 5, 251, 31))
        self.lbTrangThaiLuuTru.setObjectName("lbTrangThaiLuuTru")
        self.lbTrongKho = QtWidgets.QLabel(self.grStatusMotor)
        self.lbTrongKho.setGeometry(QtCore.QRect(160, 50, 101, 45))
        self.lbTrongKho.setAlignment(QtCore.Qt.AlignCenter)
        self.lbTrongKho.setObjectName("lbTrongKho")
        self.lbTempIn_9 = QtWidgets.QLabel(self.grStatusMotor)
        self.lbTempIn_9.setGeometry(QtCore.QRect(10, 50, 141, 45))
        self.lbTempIn_9.setObjectName("lbTempIn_9")
        self.lbChoMuon = QtWidgets.QLabel(self.grStatusMotor)
        self.lbChoMuon.setGeometry(QtCore.QRect(160, 100, 101, 45))
        self.lbChoMuon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbChoMuon.setObjectName("lbChoMuon")
        self.lbTempIn_10 = QtWidgets.QLabel(self.grStatusMotor)
        self.lbTempIn_10.setGeometry(QtCore.QRect(10, 100, 141, 45))
        self.lbTempIn_10.setObjectName("lbTempIn_10")
        self.btKiemTra = QtWidgets.QPushButton(self.grStatusMotor)
        self.btKiemTra.setGeometry(QtCore.QRect(310, 50, 161, 91))
        self.btKiemTra.setObjectName("btKiemTra")
        self.grControl = QtWidgets.QGroupBox(self.frame)
        self.grControl.setGeometry(QtCore.QRect(0, 290, 561, 441))
        self.grControl.setStyleSheet("#grControl{ border: 0px solid gray; border-radius: 0px; } ")
        self.grControl.setTitle("")
        self.grControl.setObjectName("grControl")
        self.btTroGiup = QtWidgets.QPushButton(self.grControl)
        self.btTroGiup.setGeometry(QtCore.QRect(10, 300, 171, 101))
        self.btTroGiup.setObjectName("btTroGiup")
        self.btQuanLy = QtWidgets.QPushButton(self.grControl)
        self.btQuanLy.setGeometry(QtCore.QRect(320, 300, 171, 101))
        self.btQuanLy.setObjectName("btQuanLy")
        self.btDongTu = QtWidgets.QPushButton(self.grControl)
        self.btDongTu.setGeometry(QtCore.QRect(320, 20, 171, 101))
        self.btDongTu.setObjectName("btDongTu")
        self.btMoTu = QtWidgets.QPushButton(self.grControl)
        self.btMoTu.setGeometry(QtCore.QRect(10, 20, 171, 101))
        self.btMoTu.setObjectName("btMoTu")
        self.btThongGio = QtWidgets.QPushButton(self.grControl)
        self.btThongGio.setGeometry(QtCore.QRect(10, 160, 171, 101))
        self.btThongGio.setObjectName("btThongGio")
        self.btTraCuu = QtWidgets.QPushButton(self.grControl)
        self.btTraCuu.setGeometry(QtCore.QRect(320, 160, 171, 101))
        self.btTraCuu.setObjectName("btTraCuu")
        self.grWarning = QtWidgets.QGroupBox(self.frame)
        self.grWarning.setGeometry(QtCore.QRect(690, 310, 581, 371))
        self.grWarning.setStyleSheet("#lbWarning{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}#lbCanhBao{color:#FFFF00 ;font: 75  22pt \"Ubuntu\";}.QLabel{color: rgb(255, 255, 255);font: 75 20pt \"Ubuntu\";}#lbKhoangCach{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}#lbstatusMotor{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}#lbSoNguoi{color: rgb(255, 0, 0);font: 75 Bold 22pt \"Ubuntu\";}")
        self.grWarning.setTitle("")
        self.grWarning.setObjectName("grWarning")
        self.lbCanhBao = QtWidgets.QLabel(self.grWarning)
        self.lbCanhBao.setGeometry(QtCore.QRect(160, 5, 271, 41))
        self.lbCanhBao.setObjectName("lbCanhBao")
        self.lbTempIn_7 = QtWidgets.QLabel(self.grWarning)
        self.lbTempIn_7.setGeometry(QtCore.QRect(390, 140, 81, 45))
        self.lbTempIn_7.setObjectName("lbTempIn_7")
        self.lbKhoangCach = QtWidgets.QLabel(self.grWarning)
        self.lbKhoangCach.setGeometry(QtCore.QRect(270, 140, 111, 45))
        self.lbKhoangCach.setText("")
        self.lbKhoangCach.setAlignment(QtCore.Qt.AlignCenter)
        self.lbKhoangCach.setObjectName("lbKhoangCach")
        self.lbHumiIn_3 = QtWidgets.QLabel(self.grWarning)
        self.lbHumiIn_3.setGeometry(QtCore.QRect(10, 140, 191, 41))
        self.lbHumiIn_3.setObjectName("lbHumiIn_3")
        self.lbstatusMotor = QtWidgets.QLabel(self.grWarning)
        self.lbstatusMotor.setGeometry(QtCore.QRect(220, 50, 201, 45))
        self.lbstatusMotor.setAlignment(QtCore.Qt.AlignCenter)
        self.lbstatusMotor.setObjectName("lbstatusMotor")
        self.lbSoNguoi = QtWidgets.QLabel(self.grWarning)
        self.lbSoNguoi.setGeometry(QtCore.QRect(250, 95, 141, 45))
        self.lbSoNguoi.setText("")
        self.lbSoNguoi.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSoNguoi.setObjectName("lbSoNguoi")
        self.lbHumiIn_4 = QtWidgets.QLabel(self.grWarning)
        self.lbHumiIn_4.setGeometry(QtCore.QRect(10, 50, 181, 41))
        self.lbHumiIn_4.setObjectName("lbHumiIn_4")
        self.lbHumiIn_5 = QtWidgets.QLabel(self.grWarning)
        self.lbHumiIn_5.setGeometry(QtCore.QRect(10, 95, 231, 41))
        self.lbHumiIn_5.setObjectName("lbHumiIn_5")
        self.lbWarning = QtWidgets.QLabel(self.grWarning)
        self.lbWarning.setGeometry(QtCore.QRect(10, 244, 561, 101))
        self.lbWarning.setText("")
        self.lbWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.lbWarning.setObjectName("lbWarning")
        self.lbCanhBao_2 = QtWidgets.QLabel(self.grWarning)
        self.lbCanhBao_2.setGeometry(QtCore.QRect(10, 190, 211, 41))
        self.lbCanhBao_2.setObjectName("lbCanhBao_2")
        self.btExit = QtWidgets.QPushButton(self.frame)
        self.btExit.setGeometry(QtCore.QRect(5, 5, 71, 75))
        self.btExit.setStyleSheet("border: none;background-color: none;")
        self.btExit.setText("")
        self.btExit.setObjectName("btExit")
        self.grTopMain.raise_()
        self.grTempOut.raise_()
        self.grStatusMotor.raise_()
        self.grControl.raise_()
        self.grWarning.raise_()
        self.btExit.raise_()
        self.label_2.raise_()
        SV_mainDisplay.setCentralWidget(self.centralwidget)

        self.retranslateUi(SV_mainDisplay)
        QtCore.QMetaObject.connectSlotsByName(SV_mainDisplay)

    def retranslateUi(self, SV_mainDisplay):
        _translate = QtCore.QCoreApplication.translate
        SV_mainDisplay.setWindowTitle(_translate("SV_mainDisplay", "MainWindow"))
        self.label.setText(_translate("SV_mainDisplay", "Tủ Master"))
        self.lbTempIn_2.setText(_translate("SV_mainDisplay", "Nhiệt độ ngoài : "))
        self.lbHumiIn_2.setText(_translate("SV_mainDisplay", "Độ ẩm ngoài : "))
        self.lbTempOutValue.setText(_translate("SV_mainDisplay", "0"))
        self.lbHumiOutValue.setText(_translate("SV_mainDisplay", "0"))
        self.lbTempInValue.setText(_translate("SV_mainDisplay", "0"))
        self.lbTempIn.setText(_translate("SV_mainDisplay", "Nhiệt độ trong : "))
        self.lbHumiInValue.setText(_translate("SV_mainDisplay", "0"))
        self.lbHumiIn.setText(_translate("SV_mainDisplay", "Độ ẩm trong :"))
        self.lbTrangThaiLuuTru.setText(_translate("SV_mainDisplay", "Trạng thái lưu trữ"))
        self.lbTrongKho.setText(_translate("SV_mainDisplay", "0"))
        self.lbTempIn_9.setText(_translate("SV_mainDisplay", "Trong kho :"))
        self.lbChoMuon.setText(_translate("SV_mainDisplay", "0"))
        self.lbTempIn_10.setText(_translate("SV_mainDisplay", "Cho mượn :"))
        self.btKiemTra.setText(_translate("SV_mainDisplay", "Kiểm tra"))
        self.btTroGiup.setText(_translate("SV_mainDisplay", "Trợ giúp"))
        self.btQuanLy.setText(_translate("SV_mainDisplay", "Quản lý"))
        self.btDongTu.setText(_translate("SV_mainDisplay", "Đóng tủ"))
        self.btMoTu.setText(_translate("SV_mainDisplay", "Mở tủ"))
        self.btThongGio.setText(_translate("SV_mainDisplay", "Thông gió"))
        self.btTraCuu.setText(_translate("SV_mainDisplay", "Tra cứu"))
        self.lbCanhBao.setText(_translate("SV_mainDisplay", "Trạng thái vận hành"))
        self.lbTempIn_7.setText(_translate("SV_mainDisplay", "cm"))
        self.lbHumiIn_3.setText(_translate("SV_mainDisplay", "Khoảng cách :"))
        self.lbstatusMotor.setText(_translate("SV_mainDisplay", "Đóng"))
        self.lbHumiIn_4.setText(_translate("SV_mainDisplay", "Trạng thái tủ :"))
        self.lbHumiIn_5.setText(_translate("SV_mainDisplay", "Số người trong tủ :"))
        self.lbCanhBao_2.setText(_translate("SV_mainDisplay", "Cảnh báo sự cố :"))

import resources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SV_mainDisplay = QtWidgets.QMainWindow()
    ui = Ui_SV_mainDisplay()
    ui.setupUi(SV_mainDisplay)
    SV_mainDisplay.show()
    sys.exit(app.exec_())

