# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fKetQuaTraCuu.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fKetQuaTraCuu(object):
    def setupUi(self, fKetQuaTraCuu):
        fKetQuaTraCuu.setObjectName("fKetQuaTraCuu")
        fKetQuaTraCuu.resize(1280, 800)
        fKetQuaTraCuu.setStyleSheet("")
        self.fKetQuaTraCuu = fKetQuaTraCuu
        self.frame = QtWidgets.QFrame(fKetQuaTraCuu)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.frame.setStyleSheet(".QFrame{background-image: url(:/images/darkbg.jpg);}.QPushButton:pressed { background-color: #4164ff}.QPushButton{border-radius: 18px;background-color: #FFC107;font: 75 18pt \"Arial\";}.QLabel{color:#FF8F00;font: 75 24pt \"Arial\";}.QLineEdit{background-color:#B2FF59;font: 75 32pt \"Arial\"; color: #ff0000}.QGroupBox {border: 2px solid #FFAB91;border-radius: 10px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 120, 1281, 51))
        self.label.setStyleSheet("font: 75 32pt \"Arial\";background-color: rgb(0, 0, 0);color: rgb(255, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btMo = QtWidgets.QPushButton(self.frame)
        self.btMo.setGeometry(QtCore.QRect(30, 200, 261, 61))
        self.btMo.setObjectName("btMo")
        self.btExit = QtWidgets.QPushButton(self.frame)
        self.btExit.setGeometry(QtCore.QRect(100, 700, 131, 71))
        self.btExit.setObjectName("btExit")
        self.btTrangDau = QtWidgets.QPushButton(self.frame)
        self.btTrangDau.setGeometry(QtCore.QRect(30, 300, 261, 61))
        self.btTrangDau.setObjectName("btTrangDau")
        self.btTrangTruoc = QtWidgets.QPushButton(self.frame)
        self.btTrangTruoc.setGeometry(QtCore.QRect(30, 400, 261, 61))
        self.btTrangTruoc.setObjectName("btTrangTruoc")
        self.btTrangTiepTheo = QtWidgets.QPushButton(self.frame)
        self.btTrangTiepTheo.setGeometry(QtCore.QRect(30, 500, 261, 61))
        self.btTrangTiepTheo.setObjectName("btTrangTiepTheo")
        self.btTrangCuoi = QtWidgets.QPushButton(self.frame)
        self.btTrangCuoi.setGeometry(QtCore.QRect(30, 600, 261, 61))
        self.btTrangCuoi.setObjectName("btTrangCuoi")
        self.grRight = QtWidgets.QGroupBox(self.frame)
        self.grRight.setGeometry(QtCore.QRect(500, 220, 771, 121))
        self.grRight.setStyleSheet(".QLabel{color:#FFFF00 ;font: 75  22pt \"Arial\";}")
        self.grRight.setTitle("")
        self.grRight.setObjectName("grRight")
        self.lbTiemCanPhai = QtWidgets.QLabel(self.grRight)
        self.lbTiemCanPhai.setGeometry(QtCore.QRect(20, 10, 111, 41))
        self.lbTiemCanPhai.setObjectName("lbTiemCanPhai")
        self.lbTiemCanPhai_2 = QtWidgets.QLabel(self.grRight)
        self.lbTiemCanPhai_2.setGeometry(QtCore.QRect(20, 60, 111, 41))
        self.lbTiemCanPhai_2.setObjectName("lbTiemCanPhai_2")
        self.lbTiemCanPhai_3 = QtWidgets.QLabel(self.grRight)
        self.lbTiemCanPhai_3.setGeometry(QtCore.QRect(500, 10, 111, 41))
        self.lbTiemCanPhai_3.setObjectName("lbTiemCanPhai_3")
        self.lbTiemCanPhai_4 = QtWidgets.QLabel(self.grRight)
        self.lbTiemCanPhai_4.setGeometry(QtCore.QRect(500, 60, 111, 41))
        self.lbTiemCanPhai_4.setObjectName("lbTiemCanPhai_4")
        self.leKhuVuc = QtWidgets.QLineEdit(self.grRight)
        self.leKhuVuc.setGeometry(QtCore.QRect(160, 10, 113, 41))
        self.leKhuVuc.setObjectName("leKhuVuc")
        self.leCot = QtWidgets.QLineEdit(self.grRight)
        self.leCot.setGeometry(QtCore.QRect(160, 60, 113, 41))
        self.leCot.setObjectName("leCot")
        self.leKhoang = QtWidgets.QLineEdit(self.grRight)
        self.leKhoang.setGeometry(QtCore.QRect(620, 10, 113, 41))
        self.leKhoang.setObjectName("leKhoang")
        self.leTang = QtWidgets.QLineEdit(self.grRight)
        self.leTang.setGeometry(QtCore.QRect(620, 60, 113, 41))
        self.leTang.setObjectName("leTang")
        self.grRight_2 = QtWidgets.QGroupBox(self.frame)
        self.grRight_2.setGeometry(QtCore.QRect(500, 380, 771, 91))
        self.grRight_2.setStyleSheet(".QLabel{color:#FFFF00 ;font: 75  22pt \"Arial\";}")
        self.grRight_2.setTitle("")
        self.grRight_2.setObjectName("grRight_2")
        self.lbTiemCanPhai_5 = QtWidgets.QLabel(self.grRight_2)
        self.lbTiemCanPhai_5.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.lbTiemCanPhai_5.setObjectName("lbTiemCanPhai_5")
        self.leSeri = QtWidgets.QLineEdit(self.grRight_2)
        self.leSeri.setGeometry(QtCore.QRect(212, 20, 551, 51))
        self.leSeri.setObjectName("leSeri")
        self.grRight_3 = QtWidgets.QGroupBox(self.frame)
        self.grRight_3.setGeometry(QtCore.QRect(500, 500, 771, 201))
        self.grRight_3.setStyleSheet(".QLabel{color:#FFFF00 ;font: 75  22pt \"Arial\";}")
        self.grRight_3.setTitle("")
        self.grRight_3.setObjectName("grRight_3")
        self.lbTiemCanPhai_6 = QtWidgets.QLabel(self.grRight_3)
        self.lbTiemCanPhai_6.setGeometry(QtCore.QRect(320, 30, 141, 41))
        self.lbTiemCanPhai_6.setObjectName("lbTiemCanPhai_6")
        self.leTen = QtWidgets.QLineEdit(self.grRight_3)
        self.leTen.setGeometry(QtCore.QRect(0, 100, 771, 51))
        self.leTen.setObjectName("leTen")

        self.retranslateUi(fKetQuaTraCuu)
        QtCore.QMetaObject.connectSlotsByName(fKetQuaTraCuu)

    def retranslateUi(self, fKetQuaTraCuu):
        _translate = QtCore.QCoreApplication.translate
        fKetQuaTraCuu.setWindowTitle(_translate("fKetQuaTraCuu", "Form"))
        self.label.setText(_translate("fKetQuaTraCuu", "Kết quả tra Cứu"))
        self.btMo.setText(_translate("fKetQuaTraCuu", "Mở"))
        self.btExit.setText(_translate("fKetQuaTraCuu", "Thoát"))
        self.btTrangDau.setText(_translate("fKetQuaTraCuu", "Trang đầu"))
        self.btTrangTruoc.setText(_translate("fKetQuaTraCuu", "Trang trước"))
        self.btTrangTiepTheo.setText(_translate("fKetQuaTraCuu", "Trang tiếp theo"))
        self.btTrangCuoi.setText(_translate("fKetQuaTraCuu", "Trang cuối"))
        self.lbTiemCanPhai.setText(_translate("fKetQuaTraCuu", "Khu vực :"))
        self.lbTiemCanPhai_2.setText(_translate("fKetQuaTraCuu", "Cột :"))
        self.lbTiemCanPhai_3.setText(_translate("fKetQuaTraCuu", "Khoang :"))
        self.lbTiemCanPhai_4.setText(_translate("fKetQuaTraCuu", "Tầng : "))
        self.leKhuVuc.setText(_translate("fKetQuaTraCuu", "1"))
        self.leCot.setText(_translate("fKetQuaTraCuu", "2"))
        self.leKhoang.setText(_translate("fKetQuaTraCuu", "2"))
        self.leTang.setText(_translate("fKetQuaTraCuu", "3"))
        self.lbTiemCanPhai_5.setText(_translate("fKetQuaTraCuu", "Số Seri hồ sơ :"))
        self.leSeri.setText(_translate("fKetQuaTraCuu", "AAASSSSS"))
        self.lbTiemCanPhai_6.setText(_translate("fKetQuaTraCuu", "Tên hồ sơ :"))
        self.leTen.setText(_translate("fKetQuaTraCuu", "name of file"))

        self.setEvent()

    def setEvent(self):
        self.btExit.clicked.connect(self.fKetQuaTraCuu.close)
        
import resources
